title = "Personal website of Ju-Chi Yu"

relativeURLs = true

theme = "hugo-PaperMod"

copyright = "Ju-Chi Yu"

enableRobotsTXT = true

enableEmoji = true

defaultContentLanguage = 'en'

hasCJKLanguage = true

defaultContentLanguageInSubdir: true

[languages]
  [Languages.zh-tw] 
    languageCode = "zh-tw" 
    languageName = "正體中文（臺灣）
    title = '游如淇'
    weight = 2

  [languages.en]
    title = 'Ju-Chi Yu'
    weight = 1
    

[social]
    github  = "https://github.com/juchiyu"
    twitter = "https://twitter.com/juchiyu"
    
[[menu.main]]
    name = "Home"
    url = "/home/"

[[menu.main]]
    name = "Blog"
    url = "/blog/"

[[menu.main]]
    name = "CV"
    url = "/CV/"

[[menu.main]]
    name = "About"
    url = "/about/"
    


