baseurl = "/"
relativeURLs = false
languageCode = "en-us"
title = "Ju-Chi Yu, Ph.D."
theme = "hugo-PaperMod"
copyright = "All rights reserved to Ju-Chi Yu"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]
enableEmoji = true

  [social]
    github  = "https://github.com/juchiyu"
    twitter = "https://twitter.com/juchiyu"

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/post/"

  [[menu.main]]
    name = "CV"
    url = "/CV/"

  [[menu.main]]
    name = "About"
    url = "/about/"
    
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/juchiyu"
    
  [[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/juchiyu"