title = "Ju-Chi Yu, Ph.D."

relativeURLs = true

publishDir = "../juchiyu.github.io"

theme = "hugo-PaperMod"

copyright = "All rights reserved to Ju-Chi Yu"

enableRobotsTXT = true

enableEmoji = true

defaultContentLanguage = 'en'

  [social]
    github  = "https://github.com/juchiyu"
    twitter = "https://twitter.com/juchiyu"

  [[menu.main]]
    name = "Home"
    url = "/"

  [[menu.main]]
    name = "Blog"
    url = "/blog/"

  [[menu.main]]
    name = "CV"
    url = "/CV/"

  [[menu.main]]
    name = "About"
    url = "/about/"